In [1]:
import torch

In [10]:
import numpy as np

In [ ]:
# Создайте случайный FloatTensor размера 3x4x5

In [21]:
x = torch.x = torch.randn(3, 4, 5)
x.type()

'torch.FloatTensor'

In [22]:
x

tensor([[[-0.2997,  0.0309, -0.3308, -1.4204,  0.4383],
         [ 1.7472,  1.5867, -1.7131,  1.4796, -0.5134],
         [ 0.3164,  2.0007, -0.2113,  0.0799,  0.1883],
         [ 2.3417,  0.5962,  0.0331,  0.4591, -1.0126]],

        [[-1.7777,  1.1835,  0.4383, -0.1230,  0.0051],
         [-0.8265, -0.7891, -0.7060,  1.6155,  0.0056],
         [-0.1707,  1.5116, -0.3992,  0.1264,  0.3204],
         [-0.1400,  0.6743,  0.1635, -0.4018, -0.3756]],

        [[ 0.3603, -0.9505, -0.2991,  0.4252, -0.9376],
         [-0.0696, -1.0867,  0.7070,  0.8849, -0.4276],
         [ 0.2746, -0.6548, -0.7773,  0.6397,  0.0628],
         [ 0.0849,  1.5940,  0.6640, -0.6042,  0.6311]]])

In [ ]:
# Выведите его форму (shape)

In [23]:
x.shape

torch.Size([3, 4, 5])

In [ ]:
# Приведите его к форме 6 X 10

In [24]:
x = x.reshape(6, 10)
x.shape

torch.Size([6, 10])

In [25]:
x

tensor([[-0.2997,  0.0309, -0.3308, -1.4204,  0.4383,  1.7472,  1.5867, -1.7131,
          1.4796, -0.5134],
        [ 0.3164,  2.0007, -0.2113,  0.0799,  0.1883,  2.3417,  0.5962,  0.0331,
          0.4591, -1.0126],
        [-1.7777,  1.1835,  0.4383, -0.1230,  0.0051, -0.8265, -0.7891, -0.7060,
          1.6155,  0.0056],
        [-0.1707,  1.5116, -0.3992,  0.1264,  0.3204, -0.1400,  0.6743,  0.1635,
         -0.4018, -0.3756],
        [ 0.3603, -0.9505, -0.2991,  0.4252, -0.9376, -0.0696, -1.0867,  0.7070,
          0.8849, -0.4276],
        [ 0.2746, -0.6548, -0.7773,  0.6397,  0.0628,  0.0849,  1.5940,  0.6640,
         -0.6042,  0.6311]])

In [ ]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [26]:
y = np.array([1, 4, 2, 2, 1])
for i in y:
  x *= i
x

tensor([[ -4.7946,   0.4938,  -5.2926, -22.7257,   7.0124,  27.9547,  25.3879,
         -27.4096,  23.6734,  -8.2140],
        [  5.0619,  32.0116,  -3.3814,   1.2789,   3.0132,  37.4664,   9.5395,
           0.5302,   7.3451, -16.2020],
        [-28.4426,  18.9364,   7.0124,  -1.9683,   0.0820, -13.2246, -12.6252,
         -11.2960,  25.8477,   0.0897],
        [ -2.7312,  24.1862,  -6.3877,   2.0220,   5.1261,  -2.2407,  10.7892,
           2.6164,  -6.4293,  -6.0097],
        [  5.7656, -15.2078,  -4.7863,   6.8026, -15.0022,  -1.1141, -17.3865,
          11.3115,  14.1589,  -6.8419],
        [  4.3939, -10.4771, -12.4372,  10.2354,   1.0055,   1.3583,  25.5036,
          10.6248,  -9.6678,  10.0976]])

In [ ]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [27]:
 x = x @ x.T
 x.shape

torch.Size([6, 6])

In [ ]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [69]:
from torch.autograd import Variable

x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

y = x**3 + z - 75*t

y.backward()
print(x.grad)
print(z.grad)
print(t.grad)

tensor(3.)
tensor(1.)
tensor(-75.)


In [64]:
# Создайте единичный тензор размера 5x6

In [35]:
one = torch.ones(5, 6)
one

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Переведите его в формат numpy

In [34]:
one = np.array(one)
type(one)

numpy.ndarray

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 